
all: 2mhz-vic-hires.prg 2mhz-vic-multicolor.prg

2mhz-vic-hires.prg: 2mhz-vic-hires.asm
	acme -f cbm -o 2mhz-vic-hires.prg 2mhz-vic-hires.asm
2mhz-vic-multicolor.prg: 2mhz-vic-multicolor.prg
	acme -f cbm -o 2mhz-vic-multicolor.prg 2mhz-vic-multicolor.asm
