
.PHONY: unseen-grid unseen-greydot unseen-nogreydot
.PHONY: zerox-8565r2 zerox-8565r2 zerox-6569r1 zerox-6569r5_1886_s

all: unseen-grid unseen-greydot unseen-nogreydot \
	zerox-8565r2 zerox-6569r1 zerox-6569r5_1886_s

unseen-grid:
	./anim4unseen.sh ../../../crtemulation/grid/grid.png    ./unseen-grid/unseen-grid.png           ./unseen-grid/unseen-grid

unseen-greydot:
	./anim4unseen.sh ../references/rmwtest.prg-8565.png     ./unseen-greydot/unseen-rmwtest.png     ./unseen-greydot/rmwtest
	./anim4unseen.sh ../references/videomode-v.prg-8565.png ./unseen-greydot/unseen-videomode-v.png ./unseen-greydot/videomode-v
	./anim4unseen.sh ../references/videomode-w.prg-8565.png ./unseen-greydot/unseen-videomode-w.png ./unseen-greydot/videomode-w
	./anim4unseen.sh ../references/videomode-x.prg-8565.png ./unseen-greydot/unseen-videomode-x.png ./unseen-greydot/videomode-x
	./anim4unseen.sh ../references/videomode-y.prg-8565.png ./unseen-greydot/unseen-videomode-y.png ./unseen-greydot/videomode-y
	./anim4unseen.sh ../references/videomode-z.prg-8565.png ./unseen-greydot/unseen-videomode-z.png ./unseen-greydot/videomode-z
	./anim4unseen.sh ../references/videomode1.prg-8565.png  ./unseen-greydot/unseen-videomode1.png  ./unseen-greydot/videomode1
	./anim4unseen.sh ../references/videomode2.prg-8565.png  ./unseen-greydot/unseen-videomode2.png  ./unseen-greydot/videomode2

unseen-nogreydot:
	./anim4unseen.sh ../references/rmwtest.prg-8565early.png   ./unseen-nogreydot/unseen-rmwtest.png     ./unseen-nogreydot/rmwtest
	./anim4unseen.sh ../references/videomode-v.prg.png         ./unseen-nogreydot/unseen-videomode-v.png ./unseen-nogreydot/videomode-v
	./anim4unseen.sh ../references/videomode-w.prg.png         ./unseen-nogreydot/unseen-videomode-w.png ./unseen-nogreydot/videomode-w
	./anim4unseen.sh ../references/videomode-x.prg.png         ./unseen-nogreydot/unseen-videomode-x.png ./unseen-nogreydot/videomode-x
	./anim4unseen.sh ../references/videomode-y.prg.png         ./unseen-nogreydot/unseen-videomode-y.png ./unseen-nogreydot/videomode-y
	./anim4unseen.sh ../references/videomode-z.prg.png         ./unseen-nogreydot/unseen-videomode-z.png ./unseen-nogreydot/videomode-z
	./anim4unseen.sh ../references/videomode1.prg.png          ./unseen-nogreydot/unseen-videomode1.png  ./unseen-nogreydot/videomode1
	./anim4unseen.sh ../references/videomode2.prg.png          ./unseen-nogreydot/unseen-videomode2.png  ./unseen-nogreydot/videomode2

zerox-8565r2:
	./anim4zerox.sh ../references/rmwtest.prg-8565.png     ./zerox-8565r2/8565r2_rmwtest.png     ./zerox-8565r2/8565r2_rmwtest
	./anim4zerox.sh ../references/videomode-v.prg-8565.png ./zerox-8565r2/8565r2_videomode-v.png ./zerox-8565r2/8565r2_videomode-v
	./anim4zerox.sh ../references/videomode-w.prg-8565.png ./zerox-8565r2/8565r2_videomode-w.png ./zerox-8565r2/8565r2_videomode-w
	./anim4zerox.sh ../references/videomode-x.prg-8565.png ./zerox-8565r2/8565r2_videomode-x.png ./zerox-8565r2/8565r2_videomode-x
	./anim4zerox.sh ../references/videomode-y.prg-8565.png ./zerox-8565r2/8565r2_videomode-y.png ./zerox-8565r2/8565r2_videomode-y
	./anim4zerox.sh ../references/videomode-z.prg-8565.png ./zerox-8565r2/8565r2_videomode-z.png ./zerox-8565r2/8565r2_videomode-z
	./anim4zerox.sh ../references/videomode1.prg-8565.png  ./zerox-8565r2/8565r2_videomode1.png  ./zerox-8565r2/8565r2_videomode1
	./anim4zerox.sh ../references/videomode2.prg-8565.png  ./zerox-8565r2/8565r2_videomode2.png  ./zerox-8565r2/8565r2_videomode2

zerox-6569r1:
	./anim4zerox.sh ../references/rmwtest.prg.png     ./zerox-6569r1/6569r1_rmwtest.png     ./zerox-6569r1/6569r1_rmwtest
	./anim4zerox.sh ../references/videomode-v.prg.png ./zerox-6569r1/6569r1_videomode-v.png ./zerox-6569r1/6569r1_videomode-v
	./anim4zerox.sh ../references/videomode-w.prg.png ./zerox-6569r1/6569r1_videomode-w.png ./zerox-6569r1/6569r1_videomode-w
	./anim4zerox.sh ../references/videomode-x.prg.png ./zerox-6569r1/6569r1_videomode-x.png ./zerox-6569r1/6569r1_videomode-x
	./anim4zerox.sh ../references/videomode-y.prg.png ./zerox-6569r1/6569r1_videomode-y.png ./zerox-6569r1/6569r1_videomode-y
	./anim4zerox.sh ../references/videomode-z.prg.png ./zerox-6569r1/6569r1_videomode-z.png ./zerox-6569r1/6569r1_videomode-z
	./anim4zerox.sh ../references/videomode1.prg.png  ./zerox-6569r1/6569r1_videomode1.png  ./zerox-6569r1/6569r1_videomode1
	./anim4zerox.sh ../references/videomode2.prg.png  ./zerox-6569r1/6569r1_videomode2.png  ./zerox-6569r1/6569r1_videomode2

zerox-6569r5_1886_s:
	./anim4zerox.sh ../references/rmwtest.prg.png     ./zerox-6569r5_1886_s/6569R5_1886_S_rmwtest.png     ./zerox-6569r5_1886_s/6569R5_1886_S_rmwtest
	./anim4zerox.sh ../references/videomode-v.prg.png ./zerox-6569r5_1886_s/6569R5_1886_S_videomode-v.png ./zerox-6569r5_1886_s/6569R5_1886_S_videomode-v
	./anim4zerox.sh ../references/videomode-w.prg.png ./zerox-6569r5_1886_s/6569R5_1886_S_videomode-w.png ./zerox-6569r5_1886_s/6569R5_1886_S_videomode-w
	./anim4zerox.sh ../references/videomode-x.prg.png ./zerox-6569r5_1886_s/6569R5_1886_S_videomode-x.png ./zerox-6569r5_1886_s/6569R5_1886_S_videomode-x
	./anim4zerox.sh ../references/videomode-y.prg.png ./zerox-6569r5_1886_s/6569R5_1886_S_videomode-y.png ./zerox-6569r5_1886_s/6569R5_1886_S_videomode-y
	./anim4zerox.sh ../references/videomode-z.prg.png ./zerox-6569r5_1886_s/6569R5_1886_S_videomode-z.png ./zerox-6569r5_1886_s/6569R5_1886_S_videomode-z
	./anim4zerox.sh ../references/videomode1.prg.png  ./zerox-6569r5_1886_s/6569R5_1886_S_videomode1.png  ./zerox-6569r5_1886_s/6569R5_1886_S_videomode1
	./anim4zerox.sh ../references/videomode2.prg.png  ./zerox-6569r5_1886_s/6569R5_1886_S_videomode2.png  ./zerox-6569r5_1886_s/6569R5_1886_S_videomode2
	
