
all: \
	c64modemmu-00.prg \
	c64modemmu-01.prg \
	c64modemmu-02.prg \
	c64modemmu-03.prg \
	c64modemmu-04.prg \
	c64modemmu-05.prg \
	c64modemmu-06.prg \
	c64modemmu-07.prg \
	c64modemmu-08.prg \
	c64modemmu-09.prg

c64modemmu-00.prg: c64modemmu-00.asm
	acme -f cbm -o c64modemmu-00.prg c64modemmu-00.asm

c64modemmu-01.prg: c64modemmu-01.asm
	acme -f cbm -o c64modemmu-01.prg c64modemmu-01.asm

c64modemmu-02.prg: c64modemmu-02.asm
	acme -f cbm -o c64modemmu-02.prg c64modemmu-02.asm

c64modemmu-03.prg: c64modemmu-03.asm
	acme -f cbm -o c64modemmu-03.prg c64modemmu-03.asm

c64modemmu-04.prg: c64modemmu-04.asm
	acme -f cbm -o c64modemmu-04.prg c64modemmu-04.asm

c64modemmu-05.prg: c64modemmu-05.asm
	acme -f cbm -o c64modemmu-05.prg c64modemmu-05.asm

c64modemmu-06.prg: c64modemmu-06.asm
	acme -f cbm -o c64modemmu-06.prg c64modemmu-06.asm

c64modemmu-07.prg: c64modemmu-07.asm
	acme -f cbm -o c64modemmu-07.prg c64modemmu-07.asm

c64modemmu-08.prg: c64modemmu-08.asm
	acme -f cbm -o c64modemmu-08.prg c64modemmu-08.asm

c64modemmu-09.prg: c64modemmu-09.asm
	acme -f cbm -o c64modemmu-09.prg c64modemmu-09.asm

clean:
	rm -f c64modemmu-*.prg
