
.SILENT:

# override with "make EMUDIR=foo"
EMUDIR:=../../../trunk/vice/src
#$(info $$EMUDIR is [${EMUDIR}])
#$(info using EMU: [${EMU}])

all:
	@echo "FIXME: implement 65816 tests"
	
clean:
	@echo "FIXME: implement 65816 tests"
