
all: basictest.prg printpoint.prg printpoint2.prg

basictest.prg: basictest.bas
	petcat -w2 -o basictest.prg basictest.bas
printpoint.prg: printpoint.bas
	petcat -w2 -o printpoint.prg printpoint.bas
printpoint2.prg: printpoint2.bas
	petcat -w2 -o printpoint2.prg printpoint2.bas

